import { useState } from "react";

export const useNodes = () => {
  const [nodes, setNodes] = useState([
    {
      id: "A",
      x: 50,
      y: 50,
      weight: 0,
      isStart: true,
      isFinish: false,
      distance: Infinity,
      isVisited: false,
      previousNode: null,
    },
    {
      id: "B",
      x: 400,
      y: 50,
      weight: 0,
      isStart: true,
      isFinish: false,
      distance: Infinity,
      isVisited: false,
      previousNode: null,
    },
    {
      id: "C",
      x: 150,
      y: -50,
      weight: 0,
      isStart: true,
      isFinish: false,
      distance: Infinity,
      isVisited: false,
      previousNode: null,
    },
    {
      id: "D",
      x: 300,
      y: -50,
      weight: 0,
      isStart: true,
      isFinish: false,
      distance: Infinity,
      isVisited: false,
      previousNode: null,
    },
    {
      id: "E",
      x: 250,
      y: 50,
      weight: 0,
      isStart: true,
      isFinish: false,
      distance: Infinity,
      isVisited: false,
      previousNode: null,
    },
    {
      id: "F",
      x: 150,
      y: 150,
      weight: 0,
      isStart: true,
      isFinish: false,
      distance: Infinity,
      isVisited: false,
      previousNode: null,
    },
    {
      id: "G",
      x: 300,
      y: 150,
      weight: 0,
      isStart: false,
      isFinish: true,
      distance: Infinity,
      isVisited: false,
      previousNode: null,
    },
  ]);

  return [nodes, setNodes];
};
